//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMSDivided.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestsPhoneNumbers
    {
        public int Id { get; set; }
        public string GuestMail { get; set; }
        public int PhoneNumberTypeCode { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual HotelGuests HotelGuests { get; set; }
        public virtual PhoneNumbersTypes PhoneNumbersTypes { get; set; }
    }
}
